In [128]:
import warnings
import numpy as np
warnings.simplefilter('ignore', category=RuntimeWarning) 
import pandas as pd


def fgh(x, func_type):
    if func_type == 'f':
        return 5*np.sin(x) + 0.2*x**2 + 2*x + 9
    elif func_type == 'g':
        return 3**x + 1/(2**x) - 2*x**2 - 2*x + 10
    elif func_type == 'h':
        return 0.04*x**3*(x-5)**2 + 1/(4**x) - x + 6

#導関数
def fgh_(x, func_type):
    if func_type == 'f':
        return 5*np.cos(x) + 0.4*x + 2
    elif func_type == 'g':
        return 3**x*np.log(3) - 1/(2**x)*np.log(2) - 4*x - 2
    elif func_type == 'h':
        return 0.20*x**4 - 1.6*x**3 + 3*x**2 - 1/(4**x)*np.log(4) - 1
    
arr_x0 = np.arange(-15, 11).astype(float)
arr_func = ['f', 'g', 'h']

a = 0.2
K = 4
d = 0.1
print('α = {0}, K = {1}, d = {2}\n'.format(a, K, d))
params = [a, K, d]

def GD(params, x, func):
    a, K, d = params
    for i in range(K):
        x -= a*fgh_(x, func)
        if np.abs(fgh_(x, func)) < d:
#             print(np.abs(fgh_(x, func)))
            return (i+1, x)
    return (K, x)
total_cnt = 0
result = []
for func in arr_func:
    arr_cnt = []
    arr_y = []
    min_ = float('inf')
    for x0 in arr_x0:
        cnt, x_ = GD(params, x0, func)
        total_cnt += cnt
        y = fgh(x_, func)
        if y < min_:
            x_opt = x_
            min_ = y
        arr_y.append(y)
        arr_cnt.append(cnt)
    print('{0}(x)の最小化の解: x={1}, f(x) = {2}'.format(func, x_opt, min_))
    result.append(arr_y)
    result.append(arr_cnt)
print('トータル更新回数: {0}回'.format(total_cnt))
df = pd.DataFrame(result).T
df.index = ['x0 ='+str(num) for num in arr_x0]
df.columns = ['f(x)', 'f(x)_cnt', 'g(x)', 'g(x)_cnt', 'h(x)', 'h(x)_cnt', ]
df

α = 0.2, K = 4, d = 0.1

f(x)の最小化の解: x=-7.642539087648309, f(x) = 0.5079566451790178
g(x)の最小化の解: x=-4.5531687200981175, f(x) = 1.1272489306805191
h(x)の最小化の解: x=5.04406023463801, f(x) = 0.9668238563272018
トータル更新回数: 272回

                f(x)  f(x)_cnt      g(x)  g(x)_cnt          h(x)  h(x)_cnt
x0 =-15.0  14.410212       2.0       NaN       4.0           NaN       4.0
x0 =-14.0  14.410682       1.0       NaN       4.0           NaN       4.0
x0 =-13.0  14.410187       3.0       NaN       4.0           NaN       4.0
x0 =-12.0  14.434885       4.0       NaN       4.0           NaN       4.0
x0 =-11.0   0.511512       4.0       NaN       4.0           NaN       4.0
x0 =-10.0   0.507961       3.0       NaN       4.0           NaN       4.0
x0 =-9.0    0.508152       2.0       NaN       4.0           NaN       4.0
x0 =-8.0    0.507957       2.0       NaN       4.0           NaN       4.0
x0 =-7.0    0.507967       2.0       NaN       4.0           NaN       4.0
x0 =-6.0    0.507993       3.0  3.745075       4.0           NaN       4.0
x0 =-5.0    0.616778       4.0  1.127764       4.0           NaN       4.0
x0 =-4.0    1.176820       4.0  1.127287       3.0           NaN       4.0
x0 =-3.0    1.176856       2.0  1.127249       2.0  1.303606e+24       4.0
x0 =-2.0    1.176824       1.0  1.139076       4.0  4.693513e+03       4.0
x0 =-1.0    1.176796       2.0  7.849638       4.0  5.942579e+00       4.0
x0 =0.0     1.176795       3.0  7.292235       4.0  5.879290e+00       4.0
x0 =1.0     1.176795       4.0  7.244517       3.0  5.878048e+00       2.0
x0 =2.0     9.862026       4.0  7.244586       2.0  5.918004e+00       4.0
x0 =3.0    16.403352       4.0  9.308125       4.0  9.668239e-01       4.0
x0 =4.0    16.403021       1.0       NaN       4.0  1.406050e+00       4.0
x0 =5.0    16.402546       1.0       NaN       4.0  1.386022e+00       4.0
x0 =6.0    16.402637       3.0       NaN       4.0  5.956262e+00       4.0
x0 =7.0    16.402553       2.0       NaN       4.0           NaN       4.0
x0 =8.0    16.403738       3.0       NaN       4.0           NaN       4.0
x0 =9.0    37.147662       4.0       NaN       4.0           NaN       4.0
x0 =10.0   45.390024       4.0       NaN       4.0           NaN       4.0